apiVersion: batch/v1
kind: CronJob
metadata:
  name: fcm-cronjob
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
          - name: ghcr-secret
          containers:
          - name: fcm
            image: ghcr.io/vlano003/fcm-clustering:v1.1
            command: ["python","fcm.py"]
          restartPolicy: OnFailure