apiVersion: batch/v1
kind: Job
metadata:
  name: fcm-job
spec:
  template:
    metadata:
      labels:
        app: fcm
    spec:
      containers:
      - name: fcm
        image: <your-repo>/fcm:latest
        # Якщо потрібно зберегти графік, монтуйте volume в /app/output
      restartPolicy: OnFailure