apiVersion: batch/v1
kind: CronJob
metadata:
  name: fcm-cronjob
spec:
  schedule: "0 3 * * *" # щодня о 03:00 за локальним часом
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: fcm
        spec:
          containers:
          - name: fcm
            image: ghcr.io/vlano003/fcm-clustering:latest
          restartPolicy: OnFailure