name: Deploy to Kubernetes
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    steps:
      - uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > $HOME/.kube/config
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/fcm-deployment fcm=ghcr.io/${{ github.repository_owner }}/fcm-clustering:latest --namespace default
          kubectl rollout status deployment/fcm-deployment --namespace default