ame: Build and Publish Docker Image

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and tag Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/fcm-clustering:latest
          docker build -t $IMAGE -f Docker/python/Dockerfile .
      - name: Push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/fcm-clustering:latest
          docker push $IMAGE